import type { PdfContext } from "./types";
import { draw } from "./layout";
import { drawPageHeader, drawMetaGrid, drawCalloutBox, drawTotalsBox } from "./invoice-layout";
import {
  MARGIN,
  PAGE_W,
  BODY_SIZE,
  SMALL_SIZE,
  LINE_SMALL,
  BOX_PAD,
  SPACE_12,
  TITLE_SIZE,
  SUBTITLE_SIZE,
  COVER_TITLE_SIZE,
} from "./tokens";
import type { AuditPackIncludes } from "./route-data";

const MAIN_TITLE = "GDPR Audit Pack";
const HOW_TO_USE_TITLE = "How to use this pack";
const HOW_TO_USE_BODY =
  "This pack is a read-only snapshot at export time. It supports accountability and record-keeping. It does not constitute legal advice.";

const CONTENTS_TITLE = "Contents";
/** ASCII-safe checkmark for PDF standard fonts */
const CHECK = "[x] ";

export interface CoverPageOpts {
  orgName: string;
  versionLabel: string;
  generatedAtStr: string;
  generatedByStr: string;
  includes: AuditPackIncludes;
  ropaCount: number;
  dsrCount: number;
  incidentCount: number;
  evidenceCount: number;
  auditEventCount?: number;
  logo?: import("pdf-lib").PDFImage | null;
}

/**
 * Page 1: Cover + Pack details + Contents + Snapshot totals.
 * Top-left: Go Solutions (Ireland) + logo. Main title, subtitle with date. Pack details card, how to use, contents, snapshot totals card. Footer (left/center/right) is drawn by route.
 */
export function drawCoverPage(ctx: PdfContext, opts: CoverPageOpts): void {
  // Header: logo only on left (no org title), title centre
  drawPageHeader(ctx, {
    leftTitle: "",
    centerTitle: MAIN_TITLE,
    rightMetaLines: undefined,
    logo: opts.logo ?? null,
  });

  // Subtitle: Snapshot Report — <Generated date>
  const subtitle = `Snapshot Report — ${opts.generatedAtStr}`;
  ctx.page.drawText(subtitle, {
    x: MARGIN,
    y: ctx.y,
    size: SUBTITLE_SIZE,
    font: ctx.font,
    color: ctx.colors.muted,
  });
  ctx.setY(ctx.y - SUBTITLE_SIZE - SPACE_12);

  // Pack details card
  const leftLines = [
    `Organisation: ${opts.orgName}`,
    opts.generatedByStr ? `Generated by: ${opts.generatedByStr}` : "",
  ].filter(Boolean);
  const rightLines = [
    `Version: ${opts.versionLabel}`,
    `Generated: ${opts.generatedAtStr}`,
    "Pack type: Read-only snapshot",
  ];
  drawMetaGrid(ctx, leftLines, rightLines);

  // How to use this pack
  drawCalloutBox(ctx, HOW_TO_USE_TITLE, HOW_TO_USE_BODY);

  // Contents with checkmarks
  draw(ctx, CONTENTS_TITLE, BODY_SIZE, true);
  ctx.setY(ctx.y - 6);

  const contentItems: string[] = [];
  if (opts.includes.ropa) contentItems.push(`${CHECK}Record of Processing Activities (RoPA)`);
  if (opts.includes.dsrs) contentItems.push(`${CHECK}Data Subject Requests (DSR)`);
  if (opts.includes.incidents) contentItems.push(`${CHECK}Security Incidents & Personal Data Breaches`);
  if (opts.includes.evidenceIndex) contentItems.push(`${CHECK}Accountability & Supporting Documents`);
  if (opts.includes.evidenceFiles) contentItems.push(`${CHECK}Attached files (ZIP)`);
  if (contentItems.length === 0) contentItems.push("(No sections selected)");

  const yBeforeList = ctx.y;
  for (const item of contentItems) {
    draw(ctx, item, SMALL_SIZE);
  }
  const yAfterList = ctx.y;

  // Snapshot totals card (right-aligned)
  const totalsItems: { label: string; value: string; bold?: boolean }[] = [
    { label: "RoPA records", value: opts.includes.ropa ? String(opts.ropaCount) : "Not included" },
    { label: "Open requests", value: opts.includes.dsrs ? String(opts.dsrCount) : "Not included" },
    { label: "Incidents", value: opts.includes.incidents ? String(opts.incidentCount) : "Not included" },
    { label: "Documents", value: opts.includes.evidenceIndex ? String(opts.evidenceCount) : "Not included" },
  ];
  if (opts.auditEventCount != null) {
    totalsItems.push({ label: "Audit log events", value: String(opts.auditEventCount) });
  }
  if (opts.includes.evidenceFiles) {
    totalsItems.push({ label: "ZIP attached", value: "Yes" });
  }
  totalsItems.push({
    label: "Snapshot totals",
    value: String(
      (opts.includes.ropa ? opts.ropaCount : 0) +
        (opts.includes.dsrs ? opts.dsrCount : 0) +
        (opts.includes.incidents ? opts.incidentCount : 0) +
        (opts.includes.evidenceIndex ? opts.evidenceCount : 0)
    ),
    bold: true,
  });

  ctx.setY(yBeforeList);
  drawTotalsBox(ctx, totalsItems);

  const yEnd = Math.min(yAfterList, ctx.y);
  ctx.setY(yEnd - SPACE_12);
}
