import type { PdfContext } from "./types";
import { draw } from "./layout";
import { drawPageHeader, drawMetaGrid, drawCalloutBox, drawTotalsBox } from "./invoice-layout";
import {
  MARGIN,
  PAGE_W,
  BODY_SIZE,
  SMALL_SIZE,
  LINE_SMALL,
  BOX_PAD,
  SPACE_12,
} from "./tokens";
import type { AuditPackIncludes } from "./route-data";

const HOW_TO_USE_TITLE = "How to use this pack";
const HOW_TO_USE_BODY =
  "This pack is a read-only snapshot at export time. It supports accountability and record-keeping. It does not constitute legal advice.";

const CONTENTS_TITLE = "Contents";
/** ASCII-only (WinAnsi): PDF standard fonts cannot encode Unicode checkmark. */
const CHECK = "[x] ";

export interface CoverPageOpts {
  orgName: string;
  versionLabel: string;
  generatedAtStr: string;
  generatedByStr: string;
  includes: AuditPackIncludes;
  ropaCount: number;
  dsrCount: number;
  incidentCount: number;
  evidenceCount: number;
  /** Append-only audit log event count for this org (accountability). */
  auditEventCount?: number;
  /** Pre-embedded logo (caller embeds via pdf.embedPng). */
  logo?: import("pdf-lib").PDFImage | null;
}

/**
 * Invoice-style cover: strong header, metadata grid, callout box, contents with checkmarks, totals box.
 */
export function drawCoverPage(ctx: PdfContext, opts: CoverPageOpts): void {
  // 1) Strong header: logo + org left, "GDPR Audit Pack" center, version + date right
  drawPageHeader(ctx, {
    leftTitle: opts.orgName,
    centerTitle: "GDPR Audit Pack",
    rightMetaLines: [opts.versionLabel, opts.generatedAtStr],
    logo: opts.logo ?? null,
  });

  // 2) Metadata grid (two columns)
  const leftLines = [
    `Organisation: ${opts.orgName}`,
    opts.generatedByStr ? `Generated by: ${opts.generatedByStr}` : "",
  ].filter(Boolean);
  const rightLines = [
    `Version: ${opts.versionLabel}`,
    `Generated: ${opts.generatedAtStr}`,
    "Pack type: Read-only snapshot",
  ];
  drawMetaGrid(ctx, leftLines, rightLines);

  // 3) "How to use this pack" callout box
  drawCalloutBox(ctx, HOW_TO_USE_TITLE, HOW_TO_USE_BODY);

  // 4) Contents list with checkmarks (included only); then totals box on right
  draw(ctx, CONTENTS_TITLE, BODY_SIZE, true);
  ctx.setY(ctx.y - 6);

  const contentItems: string[] = [];
  if (opts.includes.ropa) contentItems.push(`${CHECK}Data Processing Register (RoPA)`);
  if (opts.includes.dsrs) contentItems.push(`${CHECK}Customer Data Requests (DSR)`);
  if (opts.includes.incidents) contentItems.push(`${CHECK}Security Incidents (including data breaches)`);
  if (opts.includes.evidenceIndex) contentItems.push(`${CHECK}Policies & Supporting Documents`);
  if (opts.includes.evidenceFiles) contentItems.push(`${CHECK}Attached files (ZIP)`);
  if (contentItems.length === 0) contentItems.push("(No sections selected)");

  const yBeforeList = ctx.y;
  for (const item of contentItems) {
    draw(ctx, item, SMALL_SIZE);
  }
  const yAfterList = ctx.y;

  // 5) Totals box (invoice-style, right-aligned). Show 0 if included but empty; "Not included" only if excluded.
  const totalsItems: { label: string; value: string; bold?: boolean }[] = [
    {
      label: "RoPA records",
      value: opts.includes.ropa ? String(opts.ropaCount) : "Not included",
    },
    {
      label: "Open requests",
      value: opts.includes.dsrs ? String(opts.dsrCount) : "Not included",
    },
    {
      label: "Incidents",
      value: opts.includes.incidents ? String(opts.incidentCount) : "Not included",
    },
    {
      label: "Documents",
      value: opts.includes.evidenceIndex ? String(opts.evidenceCount) : "Not included",
    },
  ];
  if (opts.auditEventCount != null) {
    totalsItems.push({
      label: "Audit log (events)",
      value: String(opts.auditEventCount),
    });
  }
  if (opts.includes.evidenceFiles) {
    totalsItems.push({ label: "ZIP attached", value: "Yes" });
  }
  totalsItems.push({
    label: "Snapshot totals",
    value: String(
      (opts.includes.ropa ? opts.ropaCount : 0) +
        (opts.includes.dsrs ? opts.dsrCount : 0) +
        (opts.includes.incidents ? opts.incidentCount : 0) +
        (opts.includes.evidenceIndex ? opts.evidenceCount : 0)
    ),
    bold: true,
  });

  // Place totals box at same vertical start as list (right side)
  ctx.setY(yBeforeList);
  drawTotalsBox(ctx, totalsItems);

  // Ensure cursor is below both list and totals
  const yEnd = Math.min(yAfterList, ctx.y);
  ctx.setY(yEnd - SPACE_12);
}
